### Data analyst & Data Scientist 

Data analyst:
- SQL
- One shot 
- Programmers - MNC
- Power BI - charts


Data Scientist: - doing experiemnts in real life 
- excel
- Line by line(step)
- Python - numpy, pandas
- Open source
- Scale
- Scikit - Data prediction
- Matplot, seaborn - Charts

### Install numpy in your myenv

%pip install numpy

In [3]:
import numpy as np


## Numpy
- Works with arrays
- performance
- C language
- statstical orientated - mean, mode, standard deviation (std)  

## Shortcuts
- crtl + alt + enter --> run cell
- shift + enter --> move to next cell
- alt + enter --> run cell and move to next cell

In [32]:
marks_list = [90, 80, 20, 40]
print("list: ",marks_list*2)

marks = np.array([90, 80, 20, 40]) # Row Matrix
print("array: ",marks*2)

list:  [90, 80, 20, 40, 90, 80, 20, 40]
array:  [180 160  40  80]


Python way to double list

In [29]:
double_marks_list = list(map(lambda x: x*2, marks_list))
print(double_marks_list)

# or

double_marks_list2 =[x*2 for x in marks_list]
print(double_marks_list2)

[180, 160, 40, 80]
[180, 160, 40, 80]


In [33]:
np.ones(200) 
np.zeros(9)
np.identity(3) # Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.arange(10)
np.arange(1,10, 2)

array([1, 3, 5, 7, 9])

In [36]:
np.arange(10) > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

### Operations

- multiply, Division, Addition, subtraction
- Boolean matrix by applying conditions
- Filtering by boolean matrix  

In [142]:
np.arange(10) + 2
np.arange(10) / 2
np.arange(10) - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [38]:
np.arange(10) *2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
first_ten_nums = np.arange(1,11)
all_gt_five = first_ten_nums>5
print(first_ten_nums[all_gt_five])

# or

print(first_ten_nums[first_ten_nums>5])

[ 6  7  8  9 10]
[ 6  7  8  9 10]


## Tasks - Exercise
### Task 1

Create a 1..200 numbers and provide a numpy array with all even numbers

In [51]:
arr_nums =  np.arange(2,201,2)
print(arr_nums)

[  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100 102 104 106 108
 110 112 114 116 118 120 122 124 126 128 130 132 134 136 138 140 142 144
 146 148 150 152 154 156 158 160 162 164 166 168 170 172 174 176 178 180
 182 184 186 188 190 192 194 196 198 200]


### Task 2
Do without the step in arange

In [53]:
arr_nums1 =  np.arange(1,201)
arr_nums1[arr_nums1%2==0] 

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198, 200])

### Performance
Make random numbers in a range in a array

%%time  - to see how long something takes

In [64]:
ages = np.random.randint(18,60,10_000)
ages_list = ages.tolist()

In [71]:
%%time
double_ages = [age *2 for age in ages_list]
print(double_ages)

[48, 108, 108, 76, 116, 60, 82, 58, 78, 70, 64, 70, 100, 48, 110, 102, 76, 38, 48, 66, 116, 78, 74, 72, 112, 48, 108, 38, 80, 110, 66, 60, 38, 108, 50, 66, 42, 52, 98, 62, 98, 82, 54, 110, 98, 52, 78, 78, 90, 78, 70, 90, 106, 90, 40, 42, 38, 88, 84, 118, 62, 118, 82, 114, 86, 48, 70, 52, 112, 72, 50, 54, 46, 82, 78, 116, 90, 100, 72, 38, 114, 48, 112, 86, 46, 54, 58, 64, 40, 70, 88, 92, 54, 36, 54, 92, 90, 82, 42, 38, 68, 86, 36, 54, 114, 44, 50, 82, 94, 52, 58, 88, 36, 46, 90, 62, 98, 80, 98, 68, 108, 110, 74, 56, 98, 50, 86, 66, 80, 108, 92, 114, 64, 106, 66, 48, 52, 42, 80, 102, 108, 104, 62, 74, 40, 88, 44, 36, 76, 76, 96, 80, 88, 92, 90, 108, 52, 104, 82, 82, 60, 116, 90, 48, 44, 82, 96, 62, 48, 44, 96, 46, 110, 84, 66, 64, 46, 96, 36, 92, 112, 86, 54, 80, 112, 38, 98, 112, 44, 90, 48, 82, 70, 108, 102, 110, 44, 40, 108, 116, 82, 74, 88, 92, 116, 56, 114, 60, 58, 90, 106, 60, 92, 44, 66, 118, 58, 110, 112, 68, 66, 98, 116, 44, 96, 80, 46, 106, 38, 86, 40, 38, 108, 40, 70, 102, 80,

### statstical orientated - mean, mode, median  standard deviation (std)
- mean --> Average
- mode --> most repated number (most popular)
- meadian --> middle of the data (when sorted) middle number
- std --> standard deviation - Avergae distance between mean and numbers 

In [85]:
marks = np.random.randint(40,100,10)
print(marks)
print(marks.mean())
np.mean(marks)

[88 45 64 80 87 90 65 48 47 60]
67.4


67.4

In [86]:
np.median(marks)

64.5

In [138]:
np.sum(marks)

674

In [139]:
np.std(marks)

16.865349092147486

### Task
Investment = 1_000

rate_of_intrest --> 5%

At the end of two years. What is the balance
1st year R50 --> 1_050
2nd year -->  1_102.5
What is it after 10 years

Task 1:
Write all the years 

Task 2:
10th year value 

Task 3:
percentage increased 





In [123]:
Investment = 1_000
rate_of_intrest = 0.05 
arr_years_amount = Investment * (1 + rate_of_intrest) ** np.arange(1, 11)
print(arr_years_amount)

[1050.         1102.5        1157.625      1215.50625    1276.2815625
 1340.09564063 1407.10042266 1477.45544379 1551.32821598 1628.89462678]


In [124]:
ten_year_amount = arr_years_amount[-1]
ten_year_amount


1628.894626777442

In [137]:
percentage_increased = (ten_year_amount-Investment)/Investment
print(f"Percentage increased: {percentage_increased: .2%}") 


Percentage increased:  62.89%


### Useful methods
- max, min
- unique
- string

In [144]:
salaries = np.random.randint(1_000,10_000, 10)
print(salaries)

[4567 9623 6338 6433 4260 9247 2010 1655 9617 8533]


In [145]:
print(np.max(salaries), np.argmax(salaries))
print(np.min(salaries), np.argmin(salaries))

9623 1
1655 7


In [147]:
nums = np.random.randint(1,4, 10)
nums

array([1, 2, 1, 1, 2, 2, 2, 2, 1, 3])

In [151]:
arr_uni =np.unique(nums)
np.flip(arr_uni) # reverse a array 2d or 3d 

array([3, 2, 1])

### Task 1
find uniquie items

In [152]:
items = np.array([' Apple', 'banana ', 'GRAPE', 'cucumber', 'Pineapple', ' tomato ', 'Orange', ' lemon', 'Kiwi ', 'mango', 'blueberry ', ' raspberry'])

np.char.lower(items)
np.char.strip(items)

array(['Apple', 'banana', 'GRAPE', 'cucumber', 'Pineapple', 'tomato',
       'Orange', 'lemon', 'Kiwi', 'mango', 'blueberry', 'raspberry'],
      dtype='<U10')

In [154]:
items_unq = np.unique(np.char.lower(np.char.strip(items)))
print(items_unq)

['apple' 'banana' 'blueberry' 'cucumber' 'grape' 'kiwi' 'lemon' 'mango'
 'orange' 'pineapple' 'raspberry' 'tomato']


### Task 2
Filtering questions:

a. Find and display all items that start with the letter 'b'
b. Find and display all items that contains the letter 'e' only once 

In [161]:
items_starts_b =items_unq[np.char.startswith(items_unq,'b')]
items_with_e =items_unq[np.char.count(items_unq, 'e')==1]


print(items_starts_b)
print(items_with_e)

['banana' 'blueberry']
['apple' 'cucumber' 'grape' 'lemon' 'orange' 'raspberry']


### Task 3

hourly_visitors = [468 279  73 272 406 128 302 216 140 82]

- Total visitors in the day?
- Which is the peak hour?
- On average how many people visit per hour

In [167]:
hourly_vistitors = [468, 279,  73, 272, 406, 128, 302, 216, 140, 82]
arr_hourly_vistitors = np.array(hourly_vistitors)

print("Total visitors:", np.sum(arr_hourly_vistitors))
print("Peak hour:", np.argmax(arr_hourly_vistitors)+1)
print(f"Average visitors per hour: {round(np.mean(arr_hourly_vistitors))}/h")



Total visitors: 2366
Peak hour: 1
Average visitors per hour: 237/h


In [171]:
num_3D = np.array([[1, 3, 4],
                    [6,10,77],
                    [9, 20, 24]
                    ])

num_3D.shape

(3, 3)

In [172]:
nums1 = np.arange(1,10)
print(nums1)
nums1.shape

[1 2 3 4 5 6 7 8 9]


(9,)

In [174]:
nums1.reshape(3,3).shape


(3, 3)

In [178]:
nums_3x3 = nums1.reshape(3,3)
np.mean(nums_3x3)
np.std(nums_3x3)

2.581988897471611

In [182]:
print(nums_3x3)
np.sum(nums_3x3,axis=0) # Column
np.sum(nums_3x3,axis=1) # row
np.sum(np.sum(nums_3x3,axis=1)) # calculates for each row and then adds them - same as enitire sum

[[1 2 3]
 [4 5 6]
 [7 8 9]]


45

In [185]:
nums_3x3 + 1
nums_3x3 * 2
nums_3x3 / 2
nums_3x3 - 2

array([[-1,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7]])

In [189]:
stats = np.random.randint(40, 100, 9)
stats

array([68, 79, 86, 93, 46, 59, 68, 84, 41])

In [194]:
stats_3x3 = stats.reshape(3,3) # error if the values is more than the shape 
print(nums_3x3)

print(stats_3x3)

print("\nResults")
print(nums_3x3 + stats_3x3)
print(nums_3x3 - stats_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[68 79 86]
 [93 46 59]
 [68 84 41]]

Results
[[69 81 89]
 [97 51 65]
 [75 92 50]]
[[-67 -77 -83]
 [-89 -41 -53]
 [-61 -76 -32]]


### Task
Temperature monitor 
- temputure per room two sensors in each room  find average temperature of each room 

In [ ]:
sensor1 = np.array([[23, 25, 22],
                    [20, 21, 20],
                    [26, 25, 24]])
 
sensor2 = np.array([[24, 23, 24],
                    [22, 22, 23],
                    [25, 26, 26]])




In [198]:
avg_temp_per_room  = (sensor1 + sensor2)/2
print(avg_temp_per_room)

[[23.5 24.  23. ]
 [21.  21.5 21.5]
 [25.5 25.5 25. ]]


### Task 2

find the average tempreatre given across a suite 

In [200]:
avg_suite_temp1 = np.mean(sensor1,axis=1)
avg_suite_temp2 = np.mean(sensor2,axis=1)

print(avg_suite_temp1)
print(avg_suite_temp2)

[23.33333333 20.33333333 25.        ]
[23.66666667 22.33333333 25.66666667]


### Task 3
COmbine 3
combine the average temp of sensor 1 and sensor 2 

In [202]:
avg_temp_suite = (avg_suite_temp1 + avg_suite_temp2)/2
print(avg_temp_suite)

[23.5        21.33333333 25.33333333]
